import type { SiteTheme } from "@/lib/types";

const now = () => new Date().toISOString();

export function getDefaultTheme(): SiteTheme {
  return {
    themeName: "Premium Italian",
    primaryColor: "#0B0B0B",
    secondaryColor: "#FFFFFF",
    accentColor: "#C9A24D",
    backgroundColor: "#080808",
    textColor: "#FFFFFF",
    mutedTextColor: "#CFCFCF",
    navbarBackgroundColor: "#000000",
    footerBackgroundColor: "#050505",
    buttonPrimaryColor: "#C9A24D",
    buttonPrimaryTextColor: "#000000",
    buttonSecondaryColor: "transparent",
    buttonSecondaryTextColor: "#FFFFFF",
    cardBackgroundColor: "#111111",
    borderColor: "rgba(255,255,255,0.12)",
    fontHeading: "serif",
    fontBody: "sans",
    borderRadius: "large",
    sectionSpacing: "comfortable",
    cardSpacing: "medium",
    maxWidth: "1200px",
    buttonStyle: "premium",
    cardStyle: "photo",
    imageStyle: "cinematic",
    pageCharacter: "elegant",
    enableAnimations: true,
    animationIntensity: "subtle",
    enableParallax: true,
    enableMouseGlow: true,
    enableHoverEffects: true,
    enableSectionReveal: true,
    menuGridDesktop: 3,
    menuGridTablet: 2,
    menuGridMobile: 1,
    menuCardImageRatio: "4/5",
    menuCardTextAlign: "left",
    menuCardShowDescription: true,
    menuCardShowAllergens: false,
    menuCardShowPrice: true,
    menuCardStyle: "album",
    mobileNavbarStyle: "hamburger",
    mobileSectionSpacing: "comfortable",
    mobileImageRatio: "4/3",
    createdAt: now(),
    updatedAt: now(),
  };
}

export const THEME_PRESETS: Record<string, Partial<SiteTheme>> = {
  "Premium Italian": {
    themeName: "Premium Italian",
    primaryColor: "#0B0B0B",
    secondaryColor: "#FFFFFF",
    accentColor: "#C9A24D",
    backgroundColor: "#080808",
    textColor: "#FFFFFF",
    mutedTextColor: "#CFCFCF",
    navbarBackgroundColor: "#000000",
    footerBackgroundColor: "#050505",
    buttonPrimaryColor: "#C9A24D",
    buttonPrimaryTextColor: "#000000",
    buttonSecondaryColor: "transparent",
    buttonSecondaryTextColor: "#FFFFFF",
    cardBackgroundColor: "#111111",
    borderColor: "rgba(255,255,255,0.12)",
    buttonStyle: "premium",
    cardStyle: "photo",
    imageStyle: "cinematic",
    pageCharacter: "elegant",
  },
  "Classic White": {
    themeName: "Classic White",
    primaryColor: "#FFFFFF",
    secondaryColor: "#1C1917",
    accentColor: "#B45309",
    backgroundColor: "#FAFAF9",
    textColor: "#1C1917",
    mutedTextColor: "#57534E",
    navbarBackgroundColor: "#FFFFFF",
    footerBackgroundColor: "#F5F5F4",
    buttonPrimaryColor: "#B45309",
    buttonPrimaryTextColor: "#FFFFFF",
    buttonSecondaryColor: "transparent",
    buttonSecondaryTextColor: "#1C1917",
    cardBackgroundColor: "#FFFFFF",
    borderColor: "rgba(28,25,23,0.12)",
    buttonStyle: "filled",
    cardStyle: "bordered",
    imageStyle: "natural",
    pageCharacter: "warm",
  },
  "Dark Elegant": {
    themeName: "Dark Elegant",
    primaryColor: "#0A0A0A",
    secondaryColor: "#F5F5F4",
    accentColor: "#E7C87A",
    backgroundColor: "#050505",
    textColor: "#F5F5F4",
    mutedTextColor: "#A8A29E",
    navbarBackgroundColor: "#000000",
    footerBackgroundColor: "#0A0A0A",
    buttonPrimaryColor: "#E7C87A",
    buttonPrimaryTextColor: "#000000",
    buttonSecondaryColor: "transparent",
    buttonSecondaryTextColor: "#F5F5F4",
    cardBackgroundColor: "#141414",
    borderColor: "rgba(231,200,122,0.2)",
    buttonStyle: "outline",
    cardStyle: "photo",
    imageStyle: "cinematic",
    pageCharacter: "elegant",
  },
  "Warm Gold": {
    themeName: "Warm Gold",
    primaryColor: "#1A1208",
    secondaryColor: "#FFF8ED",
    accentColor: "#D4A017",
    backgroundColor: "#120C04",
    textColor: "#FFF8ED",
    mutedTextColor: "#D6C4A8",
    navbarBackgroundColor: "#1A1208",
    footerBackgroundColor: "#0E0903",
    buttonPrimaryColor: "#D4A017",
    buttonPrimaryTextColor: "#1A1208",
    buttonSecondaryColor: "transparent",
    buttonSecondaryTextColor: "#FFF8ED",
    cardBackgroundColor: "#22170B",
    borderColor: "rgba(212,160,23,0.25)",
    buttonStyle: "premium",
    cardStyle: "photo",
    imageStyle: "natural",
    pageCharacter: "warm",
  },
  Minimal: {
    themeName: "Minimal",
    primaryColor: "#FFFFFF",
    secondaryColor: "#111111",
    accentColor: "#111111",
    backgroundColor: "#FFFFFF",
    textColor: "#111111",
    mutedTextColor: "#6B7280",
    navbarBackgroundColor: "#FFFFFF",
    footerBackgroundColor: "#F9FAFB",
    buttonPrimaryColor: "#111111",
    buttonPrimaryTextColor: "#FFFFFF",
    buttonSecondaryColor: "transparent",
    buttonSecondaryTextColor: "#111111",
    cardBackgroundColor: "#FFFFFF",
    borderColor: "rgba(17,17,17,0.1)",
    buttonStyle: "minimal",
    cardStyle: "flat",
    imageStyle: "natural",
    pageCharacter: "modern",
    enableParallax: false,
    enableMouseGlow: false,
    animationIntensity: "subtle",
  },
};

export function applyThemePreset(presetName: string): SiteTheme {
  const preset = THEME_PRESETS[presetName];
  if (!preset) return getDefaultTheme();
  return {
    ...getDefaultTheme(),
    ...preset,
    themeName: presetName,
    updatedAt: now(),
  };
}
